### PR TITLE
[WIP] column statistics

### PR DESCRIPTION
**Pull request by aloneguid**
### Fixes

Issue #5

Column statistics calculation

### CODE REVIEW

**Comment by aloneguid** [comment]
@TikiBill

**Comment by aloneguid** [comment]
@TikiBill i've managed to move it slightly forward, not all types are supported yet though

**Comment by TikiBill** [comment]
Very nice, and a great foundation. From what I can tell this reads stats but does not calculate them and write them, which is what is needed to be useful to write parquet files for consumption with Drill. I forked and my develop branch has code to do that but I still need to test it with Drill (and the code currently has no unit tests).

I can do a pull request as the code stands now if you'd like.  Obviously you can view my proposed changes here: https://github.com/aloneguid/parquet-dotnet/compare/develop...TikiBill:develop

**Comment by aloneguid** [comment]
thanks @TikiBill i should get to your code soon, probably tomorrow

**Pull request merged**
