### PR TITLE
Add SkipDeserializingMissingColumns option to allow handling missing fields in files gracefully

### PR DESCRIPTION
**Pull request by greenlynx**
Addresses #361

### CODE REVIEW

**Review by aloneguid — COMMENTED** [review]
It looks good, thank you. I'm just wandering if it would make sense to make this a default behavior rather than opt-in. I think skipping by default is magic, and exceptions like before are not ;)

**Review by aloneguid — APPROVED** [review]
looks good to me, thanks. I'll update the docs before release.

**Comment by aloneguid** [comment]
Actually I like it too much to postpone, it's not a breaking change, just avoids more support requests. Thanks again ;)

**Comment by tukaef** [comment]
Hello, has this improvement been released in 4.16.0? I cannot find `SkipDeserializingMissingColumns` in `ParquetOptions`

**Comment by eFse7en** [comment]
> There's no option. It just magically works.

Why was this implemented as default behavior with no option to force the check?

I've just spent 2 hours debugging nulls in a column before I've realized that the new parquet file had a casing changed in a column. So the actual column was ignored without any error.

**Pull request merged**
