### PR TITLE
support reading delta byte array

### PR DESCRIPTION
**Pull request by dmishne**
### Fixes

Issue #230 

### Description

support reading delta byte array, inspired by parquet-mr impl.

- [x] I have included unit tests validating this fix.
- [x] I have updated markdown documentation where required.

### CODE REVIEW

**Comment by dmishne** [comment]
@aloneguid , regarding ReadDataPageV2Async leaks warning. Can you please provide test case where you observed the leaks? Thanks.

**Comment by aloneguid** [comment]
> @aloneguid , regarding ReadDataPageV2Async leaks warning. Can you please provide test case where you observed the leaks? I will try to resolve those as well. Thanks.

I saw its not returning pooled arrays and freeing memory but can't remember details, its was a comment to not forget to fix it.

**Comment by dmishne** [comment]
#233 - address ReadDataPageV2Async memory

**Review by aloneguid — COMMENTED** [review]
looks fine, thanks!

**Review by aloneguid — APPROVED** [review]

**Pull request merged**
