### PR TITLE
Add option to decide compression level of for instance gzip compressi…

### PR DESCRIPTION
**Pull request by dxdjgl**
…on #235

### CODE REVIEW

**Review by aloneguid — CHANGES_REQUESTED** [review]
Looks good to me. Worth updating to upcoming 1.3 of IronCompress though.

**Comment by dxdjgl** [comment]
I will change to that version right away, since I was also complaining about the performance drop due to managed snappy.

**Comment by aloneguid** [comment]
> I will change to that version right away, since I was also complaining about the performance drop due to managed snappy.

Thanks. The author of managed snappy was promising near-native performance, but i haven't benchmarked it ;)

**Comment by dxdjgl** [comment]
With my data it is 5 times slower, from ~100 second archiving to > 500 second, so for me a big step backwards.

**Comment by aloneguid** [comment]
would be interested to hear your use case in #221 if not a secret ;)

**Comment by aloneguid** [comment]
@dxdjgl IronCompress 1.3 is out, will take a few minutes for nuget.org to index it.

**Comment by aloneguid** [comment]
btw you might want to try Snappy compression instead (the default). It's faster and recent addition of logical dictionary compression will make output size similar.

**Comment by dxdjgl** [comment]
> btw you might want to try Snappy compression instead (the default). It's faster and recent addition of logical dictionary compression will make output size similar.

Similar to GZip, and better performance that sounds very interesting. I dont have much cpu but quite a bit of disk.

**Comment by dxdjgl** [comment]
@aloneguid I would rather not do the update to IronCompress 1.3 since there are some breaking changes. If you think this is fine please merge it and you could have a look at the IronCompress update.

**Comment by aloneguid** [comment]
That's fine, breaking changes are not surfacing out of parquet lib.

**Comment by dxdjgl** [comment]
> That's fine, breaking changes are not surfacing out of parquet lib.

I dont feel confident in integrating the changes so I would ask you to perform the updates.

**Comment by dxdjgl** [comment]
Thanks for spending time integrating the new IronCompress version, it will give me back performance I need.

**Review by aloneguid — APPROVED** [review]

**Pull request merged**
