### PR TITLE
Added option to chose compression method to FileMerger, and to specify the custom metadata of the output file.

### PR DESCRIPTION
**Pull request by dxdjgl**

### CODE REVIEW

**Comment by dxdjgl** [comment]
@aloneguid what do you think about this extension of the new FileMerger?

**Review by aloneguid — APPROVED** [review]
Sorry for the delay, looks good, merging!

**Comment by dxdjgl** [comment]
Thank you very much.

**Comment by aloneguid** [comment]
No thank you! It's in the latest prerelease nugget.

**Pull request merged**
