### PR TITLE
fix: decimal scale condition

### PR DESCRIPTION
**Pull request by sierzput**
Fix for #503

### CODE REVIEW

**Comment by sierzput** [comment]
Hi @aloneguid, I introduced small fix, but there are some failing tests for macos-latest. Could you help me with them? I'm not sure if it's connected to my change.

**Comment by aloneguid** [comment]
mac builds were failing due to M1 issues with java, it's all good now

**Review by aloneguid — APPROVED** [review]
LGTM

**Comment by mshatnawi** [comment]
Is this fix included in version 4.24.0-pre.1, and if not what version should I rollback to avoid this issue?

**Pull request merged**
